spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: tanghai1289@gmail.com
    password: kovz guaq shtt lzce
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  application:
    name: guard
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    #Work
#    url: jdbc:postgresql://localhost:5432/configure kovz guaq shtt lzce
#    username: postgres
#    password: 309927605

    #HOME
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin

  jpa:
    open-in-view: false

    #Personal
#    url: jdbc:postgresql://localhost:5432/merchant
#    username: postgres
#    password: admin

backend_server:
  web_url: http://localhost:5173

jwt:
  secret_key: aVeryLongSecretKeyThatIsAtLeastSixtyFourCharactersLongForHS512Encryption!!!
  expiration-ms: 840000

setting:
  enableSaveLog: true
  enableRegister: true

server:
  rate_limit: 100
  servlet:
    context-path: /guard
  port: 8080

app:
  version: 1.0.10