spring:
#  profiles:
#    active: local
  application:
    name: guard
  mail:
    host: smtp.gmail.com
    port: 587
    username: tanghai1289@gmail.com
    password: ${GM_PWD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_HOST}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: ${JPA_VIEW_MODE}

backend_server:
  web_url: ${FRONTEND_URL}
  gm_pwd: ${GM_PWD}

jwt:
  secret_key: ${JWT_SECRET_KEY}
  expiration-ms: 840000

setting:
  enableSaveLog: ${ENABLE_SAVE_LOG}
  enableRegister: ${ENABLE_REGISTER}

server:
  rate_limit: ${RATE_LIMIT}
  servlet:
    context-path: /guard
  port: 8080

telegram:
  enable: ${TELEGRAM_BOT_ENABLE}
  bot-token: ${TELEGRAM_BOT_TOKEN}
  chat-id: ${TELEGRAM_CHAT_ID}

app:
  version: 1.1.12